name: FischersFiresidechatsInternational
favicon: null
layout_spectrum: 0.020807283464819193
typography_spectrum: 0.04792184731923044
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5127020296640694
  lightness: 0.4948072759434581
  saturation: 0.5640168781392276
  rhythmicContrast: 0.30402110633440316
purpose: []
